name: yapa
description: Yet another pantry app.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  uuid: ^2.0.4
  image_picker: ^0.6.4
  transparent_image: ^1.0.0
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_slidable: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.12.0
  bloc_test: ^3.1.0
  quiver: ^2.0.5
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  flutter_launcher_icons: ^0.7.4

dependency_overrides:
  quiver: ^2.0.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon/icon.png"